# Generated by Django 2.2.19 on 2022-08-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_unique_id', models.CharField(default='SOME STRING', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, choices=[('demo', 'Demo'), ('pro', 'Pro'), ('classic', 'Classic'), ('premium', 'Premium')], max_length=255, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_old_curriculum', models.BooleanField(default=False)),
                ('open_course', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopularVideosPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=30)),
                ('courses', models.ManyToManyField(to='videoapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='PopularVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video_key', models.TextField()),
                ('order_no', models.IntegerField(blank=True, default=-1, null=True)),
                ('popular_videos_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videoapp.PopularVideosPlaylist')),
            ],
        ),
    ]
