# Generated by Django 2.2.19 on 2022-08-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_auto_20220827_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularvideosplaylist',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='popularvideosplaylist',
            name='playlist_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='popularvideosplaylist',
            name='updated_by',
            field=models.CharField(max_length=30),
        ),
    ]
